### PR TITLE
Display errors in file conversion

### PR DESCRIPTION
**Pull request by adamchalmers**
Part of #352

Test: run `cargo run -- file convert --output-format gltf ~/Downloads/kitt.ply ./`

Before this PR:

```
Unexpected Response: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.kittycad.io")), port: None, path: "/file/conversion/ply/gltf", query: None, fragment: None }, status: 400, headers: {"date": "Wed, 13 Sep 2023 18:18:47 GMT", "content-type": "application/json", "content-length": "168", "x-request-id": "9d9d208e-73ed-45cc-988a-6ef30e7e62e9", "strict-transport-security": "max-age=15724800; includeSubDomains", "cf-cache-status": "DYNAMIC", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=DuqbgM4pRYX9FL2l3QBWvrUgoYsQWQrcPyB7JtpUyhlAxF%2FI2uK%2BQXpghYFFWvYgxd28rJQZ2zlEV5kL0fpDBLOnjhEAFexYr3DuuaFV%2FPdW4QJQq2lhk5w7QEuE0BoepI8yANg6qOvsQTj%2Bpho%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "set-cookie": "__cflb=02DiuForeBv2DVnYSFPtSfNRmR8hoJ4HciYZCksQzHXLG; SameSite=Lax; path=/; expires=Thu, 14-Sep-23 17:18:47 GMT; HttpOnly", "server": "cloudflare", "cf-ray": "80626505b9b0439d-EWR", "alt-svc": "h3=\":443\"; ma=86400"} }
```

After:

```
Error:
{
  "request_id": "e761e2b7-f80d-4e0f-b8ac-0fe3dcd6dcba",
  "error_code": "InvalidRequest",
  "message": "could not convert file: PLY mesh face has no vertex indices"
}
```

This isn't ideal, we can definitely do better, but this is an improvement.

### CODE REVIEW

**Comment by jessfraz** [comment]
niceeeeee

**Comment by jessfraz** [comment]
also seems like maybe a bug?

**Comment by jessfraz** [comment]
the fact that it didnt work

**Review by jessfraz — APPROVED** [review]

**Comment by adamchalmers** [comment]
Yeah there's a separate issue for that bug

**Comment by adamchalmers** [comment]
Hey @jessfraz the API should be sending "invalid_request" not "InvalidRequest"

**Pull request merged**
